#!/usr/bin/with-contenv bash

echo 
echo "Checking structure:"
if [ ! -d ${CONFDIR} ]; then
    echo "-> CONFIG dir not found" && exit 1
else

    printf "   %s\n" "-> Directories"
    printf "       %s" "worlds..."
    if [ ! -d ${CONFDIR}/worlds ]; then mkdir -p ${CONFDIR}/worlds && printf " %s\n" "CREATED"; 
        else printf " %s\n" "FOUND"
            for d in "${CONFDIR}/worlds/"*; do
                #basename $d
                printf "         %\n" "$d"
            done
        fi
    printf "       %s" "plugins..."
    if [ ! -d ${CONFDIR}/plugins ]; then mkdir -p ${CONFDIR}/plugins&& printf " %s\n" "CREATED"; 
        else printf " %s\n" "FOUND"; fi

    files=( banned-ips.json banned-players.json ops.json permissions.yml usercache.json whitelist.json )
    printf "   %s\n" "-> Files"
    for i in "${files[@]}"
        do
        printf "       %s" "$i..."
        if [ ! -f ${CONFDIR}/$i ]; then 
            printf " %s" "MISSING"
            if [ -f ${APPDIR}/$i ]; then #? CHECK IF IT IS A LINK, BUT SHOULD NOT EXIST, CAUSE WILL BE CREATED AFTER EACH START
                mv ${APPDIR}/$i ${CONFDIR}/$i
                rm -rf ${APPDIR}/$i
                ln -s ${CONFDIR}/$i ${APPDIR}/$i
                printf " %s\n" " -> GENERATED"
            else
                printf " %s\n" "-> WARNING: $i not Found. Maybe frist run ?"
            fi
        else
            printf " %s" "FOUND"
            ln -sf ${CONFDIR}/$i ${APPDIR}/$i
            printf " %s\n" "-> LINK GENERATED"
        fi
    done
fi
echo
echo "Setting owner, current settings are:"
chown -R app:app /app
chown -R app:app /config
echo
ls -l / | grep app | awk 'NR > 1 { print " -> " $1 " " $3 ":" $4 " /" $9 }'
echo 
printf "%s" "Done" && printf ' %s\n' "Status OK"
echo