#!/usr/bin/with-contenv bash

echo 
echo "Checking structure:"
if [ ! -d ${CONFDIR} ]; then
    echo "-> CONFIG dir not found" && exit 1
else

    printf "   %s\n" "-> Directories"
    
    printf "       %s" "worlds... " #i WORLDS
    if [ ! -d ${CONFDIR}/worlds ]; then mkdir -p ${CONFDIR}/worlds && printf " %s\n" "CREATED"; 
        else printf " %s\n" "FOUND"
            for d in "${CONFDIR}/worlds/"*; do
                bn=$(basename $d)
                printf "         %s\n" "$bn"
            done
        fi
    
    printf "      %s" " server... " #i SERVER
    if [ ! -d ${CONFDIR}/server ]; then 
        mkdir -p ${CONFDIR}/server && printf " %s" "CREATED"
        cp ${APPDIR}/spigot.jar ${CONFDIR}/server/spigot.jar && printf ", %s\n" "LOADED DEFAULT SERVER JAR" #! SHOW DEFAULT VERSION
    else
        jarn=$(find ${CONFDIR}/server -name '*.jar' | sed 's/\/config\/server\///') #! ADD VAR CONFDIR
        printf " %s" "FOUND" && printf " %s\n" "WITH $jarn" 
    fi

    printf "       %s" "plugins..." #i PLUGINS
    if [ ! -d ${CONFDIR}/plugins/current ]; then mkdir -p ${CONFDIR}/plugins/current && printf " %s" "CREATED"; else printf " %s" "FOUND"; fi
    if [ ! -L ${CONFDIR}/server/plugins ]; then ln -s ${CONFDIR}/plugins/current ${CONFDIR}/server/plugins && printf ", %s\n" "LINKED"; else printf ", %s\n" "LINK EXISTS"; fi

fi
echo
echo "Setting owner, current settings are:"
chown -R app:app /app
chown -R app:app /config
echo
ls -l / | grep app | awk 'NR > 1 { print " -> " $1 " " $3 ":" $4 " /" $9 }'
echo 
echo "Setting scripts permission, current settings are:"
for f in /app/bin/* ; do chmod +x "$f" ; done
echo
ls -l /app/bin | awk 'NR > 1 { print " -> " $1 " " $3 ":" $4 " /" $9 }'
echo
printf "%s" "Done" && printf ' %s\n' "Status OK"
echo